version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.12
    steps:
      - checkout
      - run: make test
  benchmark:
    docker:
      - image: golang:1.12
    steps:
      - checkout
      - run: go get github.com/kinche/franz-agent
      - run: franz-agent --token 123 --cmd="make benchmark" 
workflows:
  version: 2
  test-and-benchmark:
    jobs:
      - build
      - benchmark