version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.12
    steps:
      - checkout
      - run: make test
  benchmark:
    docker:
      - image: golang:1.12
    steps:
      - checkout
      - run: make benchmark 
workflows:
  version: 2
  test-and-benchmark:
    jobs:
      - build
      - benchmark